### ISSUE TITLE
pyproject.toml usage doesn't work

### ISSUE THREAD

**Issue by kasium** [hakancelikdev/unimport#209]
I use the following commands and files

```shell
unimport foo --config pyproject.toml 
```

```toml
[tool.unimport]
exclude = "foo/_whatever"
remove = true
```

However, unused imports are not removed and paths I configured are not excluded. I guess this is related to 
`config = config.merge(**vars(args))`, because the default config has already values for exclude and remove and these overwrite my configured ones.
