### ISSUE TITLE
Args in .pre-commit-config.yaml are being ignored

### ISSUE THREAD

**Issue by dennisrei** [hakancelikdev/unimport#259]
When I run the pre-commit the provided arguments are being ignored. Or atleast ignore-init is being ignored.

`- repo: https://github.com/hakancelik96/unimport
    rev: 0.12.1
    hooks:
      - id: unimport
        name: unimport (Remove unused imports)
        args:
          [
            --remove,
            --include-star-import,
            --ignore-init,
            --gitignore
          ]`

**Comment by hakancelikdev** [comment]
Thanks for reporting this issue, I will fix it as soon as possible, It looks like we mistyped the pre-commit configuration in the document.

Can you try the one below?


```
repos:
  - repo: https://github.com/hakancelikdev/unimport
    rev: stable
    hooks:
      - id: unimport
        args: 
          - --remove
          - --include-star-import
          - --ignore-init
          - --gitignore
```
